name: rl_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=13.1.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.10.12
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - alembic==1.11.3
      - anyio==3.7.1
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - box2d-py==2.3.5
      - cachetools==5.3.1
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - click==8.1.6
      - cloudpickle==2.2.1
      - cmaes==0.10.0
      - cmake==3.25.0
      - colorlog==6.7.0
      - comm==0.1.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.2
      - executing==1.2.0
      - farama-notifications==0.0.4
      - fastjsonschema==2.18.0
      - filelock==3.9.0
      - fonttools==4.42.0
      - fqdn==1.5.1
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - greenlet==2.0.2
      - grpcio==1.57.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.0
      - idna==3.4
      - ipykernel==6.25.0
      - ipython==8.14.0
      - isoduration==20.11.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.18.6
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - kiwisolver==1.4.4
      - lit==15.0.7
      - mako==1.2.4
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mistune==3.0.1
      - mpmath==1.2.1
      - namedlist==1.8
      - nbclient==0.8.0
      - nbconvert==7.7.3
      - nbformat==5.9.2
      - nest-asyncio==1.5.7
      - networkx==3.0
      - notebook==7.0.2
      - notebook-shim==0.2.3
      - numpy==1.25.2
      - oauthlib==3.2.2
      - optuna==3.3.0
      - overrides==7.4.0
      - packaging==23.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.3.0
      - platformdirs==3.10.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.0
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygame==2.5.0
      - pygments==2.16.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pyyaml==6.0.1
      - pyzmq==25.1.0
      - referencing==0.30.2
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.9.2
      - rsa==4.9
      - send2trash==1.8.2
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - sqlalchemy==2.0.20
      - stack-data==0.6.2
      - swig==4.1.1
      - sympy==1.11.1
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.3.2
      - tqdm==4.65.1
      - traitlets==5.9.0
      - triton==2.0.0
      - typing-extensions==4.7.1
      - uri-template==1.3.0
      - urllib3==1.26.16
      - wandb==0.15.8
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.3.6
      - --index-url https://download.pytorch.org/whl/cu118
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118

